# Generated by Django 5.2.1 on 2025-05-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('paginas', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('genero', models.CharField(choices=[('ROM', 'Romance'), ('FIC', 'Ficção'), ('REL', 'Religioso'), ('INF', 'Infantil'), ('JUV', 'Juvenil'), ('NFC', 'Não Ficção'), ('SUS', 'Suspense'), ('TER', 'Terror')], max_length=3)),
                ('disponivel', models.BooleanField(default=True)),
            ],
        ),
    ]
