# Generated by Django 5.2.1 on 2025-05-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livros',
            old_name='genero',
            new_name='genero1',
        ),
        migrations.AddField(
            model_name='livros',
            name='genero2',
            field=models.CharField(choices=[('ROM', 'Romance'), ('FIC', 'Ficção'), ('REL', 'Religioso'), ('INF', 'Infantil'), ('JUV', 'Juvenil'), ('NFC', 'Não Ficção'), ('SUS', 'Suspense'), ('TER', 'Terror')], default='Romance', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livros',
            name='genero3',
            field=models.CharField(choices=[('ROM', 'Romance'), ('FIC', 'Ficção'), ('REL', 'Religioso'), ('INF', 'Infantil'), ('JUV', 'Juvenil'), ('NFC', 'Não Ficção'), ('SUS', 'Suspense'), ('TER', 'Terror')], default='Terror', max_length=3),
            preserve_default=False,
        ),
    ]
