# Generated by Django 5.2.1 on 2025-05-19 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_rename_genero_livros_genero1_livros_genero2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livros',
            old_name='disponivel',
            new_name='disponível',
        ),
        migrations.RenameField(
            model_name='livros',
            old_name='genero1',
            new_name='gênero_1',
        ),
        migrations.RenameField(
            model_name='livros',
            old_name='genero2',
            new_name='gênero_2',
        ),
        migrations.RenameField(
            model_name='livros',
            old_name='genero3',
            new_name='gênero_3',
        ),
        migrations.RenameField(
            model_name='livros',
            old_name='paginas',
            new_name='páginas',
        ),
        migrations.RenameField(
            model_name='livros',
            old_name='titulo',
            new_name='título',
        ),
    ]
