# Generated by Django 5.2.1 on 2025-05-19 18:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_rename_disponivel_livros_disponível_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livros',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
